# These are supported funding model platforms

github: [Puddlz1]  # Replace with your actual GitHub username
patreon: # Replace with your Patreon username if you have one
open_collective: # Replace with your Open Collective username if you have one
ko_fi: # Replace with your Ko-fi username if you have one
liberapay: # Replace with your Liberapay username if you have one
custom: # Replace with a custom URL if you have one